[package]
name = "framodel-attest"
version = "0.1.0"
compiler = "0.12.0"
entrypoint = "lib.typ"
authors = ["Louis Guichard <glpda+git@pm.me>"]
license = "MIT"
description = "French affidavit template - mod√®le d'attestation sur l'honneur."
repository = "https://github.com/glpda/framodel"
keywords = ["administration", "letter"]
categories = ["office"]
disciplines = ["law"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
